services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:v1
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - my_network
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:v1
    volumes:
      - wp_data:/var/www/html
    env_file:
      - ./.env
    networks:
      - my_network
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:v1
    volumes:
      - wp_data:/var/www/html
    networks:
      - my_network
    restart: always
    ports:
      - 443:443

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/salee2/data/mariadb"
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/salee2/data/wordpress"

networks:
  my_network:
    driver: bridge
