version: '3.8'

services:
  mariadb:
    image: mariadb:v1
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - my_network

  wordpress:
    image: wordpress:v1
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp_data:/var/www/html 
    networks:
      - my_network
    restart: always
    env_file:
      - ./.env
    depends_on:
      - mariadb

  nginx:
    image: nginx:v1
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wp_data:/var/www/html 
    networks:
      - my_network
    ports:
      - 443:443
    depends_on: 
      - wordpress

volumes:
  db_data:
  wp_data:

networks:
  my_network:
    driver: bridge
