version: '3.8'

services:
  db:
    # container_name: name
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - my_network

  wordpress:
    # image: wordpress:latest
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp_data:/var/www/html 
    networks:
      - my_network
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wp_data:/var/www/html 
    networks:
      - my_network
    # volumes:
    #   - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 443:443
    depends_on: 
      - wordpress

volumes:
  db_data:
  wp_data:

networks:
  my_network:
    driver: bridge
