FROM debian:bookworm

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y mariadb-server

COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./tools/docker-entrypoint.sh /

RUN chmod +x /docker-entrypoint.sh

EXPOSE 3306

ENTRYPOINT [ "/docker-entrypoint.sh" ]

# CMD ["/sbin/mysqld"]