version: '3.8'

services:
  db:
    build: 
      context: .
      dockerfile: mariadb/Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./env/mariadb.env

  wordpress:
    # image: wordpress:latest
    build: 
      context: .
      dockerfile: wordpress/Dockerfile
    volumes:
      - wp_data:/var/www/html 
    restart: always
    env_file:
      - ./env/wordpress.env
    depends_on:
      - db

  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - wp_data:/var/www/html 
    # volumes:
    #   - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 443:443
    depends_on: 
      - wordpress

volumes:
  db_data:
  wp_data: