services:
  db:
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./env/mariadb.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html 
    restart: always
    env_file:
      - ./env/wordpress.env
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on: 
      - wordpress

volumes:
  db_data:
  wp_data: