FROM debian:bookworm

RUN apt-get -y update && apt-get install -y mariadb-server

COPY ./mariadb/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./mariadb/docker-entrypoint.sh /

RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT [ "/docker-entrypoint.sh" ]

#CMD ["mariadbd"]